version: '3'

services:

  entrypoint_app:
    container_name: entrypoint_app
    env_file: .env
    build: entrypoint_app
    networks:
      - main-network

  elasticsearch:
    container_name: ${ES_HOST}
    env_file: .env
    image: elasticsearch:8.11.4
    expose:
      - ${ES_PORT}
    volumes:
      - el_data:/usr/share/elasticsearch/data
    environment:
      ELASTIC_USERNAME: ${ES_USER}
      ELASTIC_PASSWORD: ${ES_PASSWORD}
      ES_JAVA_OPTS: "-Xms200m -Xms200m"
      discovery.type: single-node
      xpack.security.enabled: false
    networks:
      - main-network


  postgresql:
    container_name: ${PG_HOST}
    env_file: .env
    image: postgres:16.2
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    expose:
      - ${PG_PORT}
    networks:
      - main-network


  redis:
    container_name: ${REDIS_HOST}
    env_file: .env
    image: redis:7.2.4
    expose:
      - ${REDIS_PORT}
    networks:
      - main-network


  postgres_to_es:
    container_name: ${PG_TO_ES_HOST}
    env_file: .env
    build: postgres_to_es
    networks:
      - main-network


  fastapi_solution:
    container_name: ${FASTAPI_HOST}
    env_file: .env
    build: fastapi_solution
    expose:
      - ${FASTAPI_PORT}
    networks:
      - main-network


  nginx:
    container_name: ${NGINX_HOST}
    env_file: .env
    image: nginx:1.25.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    networks:
      - main-network


networks:
  main-network:
    external: true

volumes:
  el_data:
  pg_data: